# -*- coding: utf-8 -*-
"""Calculo de Area.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Lvd3PUHs2fEiNd8QMDhX7OuG4TtOmXY
"""

# Calculo de Área
import math
raio = 23
area = math.pi * raio**2
print("A area é: ",round(area,2))