# -*- coding: utf-8 -*-
"""Calculo de IMC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TAIruCIU1Cll5MKgFKC6iRopw9OtGyEx
"""

#Calculo do IMC
peso = float(input("Digite seu peso: "))
altura = float(input("Digite sua altura: "))

imc = peso / altura**2
print("O IMC é: ",round(imc,2))

if imc < 18.5:
    print("Abaixo do peso")
elif imc == 18.5 or imc < 25:
    print("Peso normal")
elif imc == 25 or imc < 30:
    print("Acima do peso")
else:
    print("Obeso")

if imc < 18.5:
    print("Abaixo do peso")
elif imc >= 18.5 and imc < 25:
    print("Peso normal")
elif imc >= 25 and imc < 30:
    print("Acima do peso")
else:
    print("Obeso")