# -*- coding: utf-8 -*-
"""Vetor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jj76prI4zQ63n1W2JL8taKn__X16TMEc
"""

vetor = [1, 2, 3, 4, 5]
vetor.append(78)
vetor.append(81)
print(vetor)

vetor = ["laranja", "Banana", "Pera"]
vetor.append(78)
vetor.append(81)
print(vetor)